name: RDN Pool Check Alive Ban Job

permissions:
  contents: write

# 每两天检测一次 凌晨四点
on:
  schedule:
    - cron: "0 4 */2 * *" # 每2天凌晨两点检测一次dns解析的ip是否被防火墙ban

#on:
#  push:
#    branches:
#      - master # Replace with your branch name

jobs:
  daily_build:
    name: crontab run for update
    runs-on: ubuntu-latest
    env:
      CF_APIKEY: ${{ secrets.CF_APIKEY }}
      CF_EMAIL: ${{ secrets.CF_EMAIL }}
      CF_ZONEID: ${{ secrets.CF_ZONEID }}
      CF_DNSRECORDTYPE: ${{ secrets.CF_DNSRECORDTYPE }}
      CF_DNSRECORDNAME: ${{ secrets.CF_DNSRECORDNAME}}
      IPPICK_MODE: ${{ secrets.IPPICK_MODE}}


    steps:
      # Step 1: run a standard checkout action
      - name: Checkout target repo
        uses: actions/checkout@v3

      - name: Set Up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.4

      - name: Run MidNight Ban check task
        run: |
          ./bbt-updater -p true